09-05-2023 11:17:38 $ Using device='cuda'
09-05-2023 11:17:38 $ Experiment 1/3
Model with configuration: dataset=CIFAR10, model=ResNet18, embedding_dim=1024, whitening=ZCA, num_unfrozen_layers=1, ind. loss=NegApproxLoss1, reg. loss=None, class. loss=Enable, batch=10/40, margin=0.2, num_epochs_in_step=1, num_epoch_steps=5
09-05-2023 12:53:28 $ loss = 4.54, ranking_loss = 0.27, regularization_loss = 0.00, independence_loss = 1.96, classification_loss = 2.30, accuracy = 0.21
09-05-2023 14:36:37 $ loss = 4.15, ranking_loss = 0.22, regularization_loss = 0.00, independence_loss = 1.63, classification_loss = 2.30, accuracy = 0.61
09-05-2023 16:20:22 $ loss = 4.02, ranking_loss = 0.21, regularization_loss = 0.00, independence_loss = 1.51, classification_loss = 2.30, accuracy = 0.69
09-05-2023 18:04:04 $ loss = 3.97, ranking_loss = 0.21, regularization_loss = 0.00, independence_loss = 1.47, classification_loss = 2.30, accuracy = 0.72
09-05-2023 19:47:21 $ loss = 3.95, ranking_loss = 0.20, regularization_loss = 0.00, independence_loss = 1.45, classification_loss = 2.30, accuracy = 0.75
09-05-2023 19:49:01 $ Experiment 2/3
Model with configuration: dataset=CIFAR10, model=ResNet18, embedding_dim=1024, whitening=ZCA, num_unfrozen_layers=1, ind. loss=NegApproxLoss1, reg. loss=None, class. loss=Enable, batch=10/10, margin=0.2, num_epochs_in_step=1, num_epoch_steps=5
10-05-2023 02:25:31 $ loss = 4.19, ranking_loss = 0.23, regularization_loss = 0.00, independence_loss = 1.67, classification_loss = 2.29, accuracy = 0.60
10-05-2023 09:03:24 $ loss = 3.97, ranking_loss = 0.21, regularization_loss = 0.00, independence_loss = 1.48, classification_loss = 2.28, accuracy = 0.67
10-05-2023 15:58:28 $ loss = 3.81, ranking_loss = 0.29, regularization_loss = 0.00, independence_loss = 1.47, classification_loss = 2.05, accuracy = 0.63
10-05-2023 22:41:37 $ loss = 3.34, ranking_loss = 0.49, regularization_loss = 0.00, independence_loss = 1.49, classification_loss = 1.37, accuracy = 0.73
11-05-2023 05:15:48 $ loss = 3.05, ranking_loss = 0.49, regularization_loss = 0.00, independence_loss = 1.50, classification_loss = 1.07, accuracy = 0.77
11-05-2023 05:17:35 $ Experiment 3/3
Model with configuration: dataset=CIFAR10, model=ResNet18, embedding_dim=1024, whitening=ZCA, num_unfrozen_layers=1, ind. loss=NegApproxLoss1, reg. loss=None, class. loss=Enable, batch=5/5, margin=0.2, num_epochs_in_step=1, num_epoch_steps=5
11-05-2023 11:09:21 $ Caught an exception in main
Traceback (most recent call last):
  File "main.py", line 132, in main
    database_embeddings, database_labels = run_inference(
  File "/home/mark.sherman/Projects/Personal/independence-inducing-loss/model.py", line 201, in run_inference
    embeddings, labels = zip(*trainer.predict(model, dataloaders=dataloader))
TypeError: type object argument after * must be an iterable, not NoneType
